apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edo2
  namespace: continuous-delivery
spec:
  project: default
  source:
    repoURL: 'https://github.com/MToscanoM/gitops-labs-sistemas.git'
    targetRevision: HEAD
    path: argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: continuous-delivery
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
  ignoreDifferences:
  # for the specified json pointers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
