apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-k-cert
  namespace: continuous-delivery #argocd namespace
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/MToscanoM/gitops-labs.git'
    path: ./aplicaciones/app1-kustomize/envs/cert
    targetRevision: v1.1-cert
  - repoURL: 'https://github.com/MToscanoM/gitops-labs-sistemas.git'
    path: ./app1-kustomize/envs/cert
    targetRevision: v1.1-cert
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1-k-cert
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
