apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-k-prod
  namespace: continuous-delivery #argocd namespace
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/MToscanoM/gitops-labs.git'
    path: ./aplicaciones/app1-kustomize/envs/prod
    targetRevision: v1.0-pro
  - repoURL: 'https://github.com/MToscanoM/gitops-labs-sistemas.git'
    path: ./app1-kustomize/prod
    targetRevision: v1.1-prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1-k-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
